import React, { useState, useEffect } from 'react';
import {
  AdvisoryRecommendation,
  AdvisorySummary,
  RecommendationStatus,
  RecommendationSeverity
} from '../types/twin';
import {
  fetchRecommendations,
  fetchAdvisorySummary,
  reviewRecommendation,
  triggerRuleEvaluation
} from '../services/api';

interface AdvisoryCenterModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectEntity?: (entityId: string) => void;
  onOpenScenarioStudio?: () => void;
}

export const AdvisoryCenterModal: React.FC<AdvisoryCenterModalProps> = ({
  isOpen,
  onClose,
  onSelectEntity,
  onOpenScenarioStudio
}) => {
  const [recommendations, setRecommendations] = useState<AdvisoryRecommendation[]>([]);
  const [summary, setSummary] = useState<AdvisorySummary | null>(null);
  const [domainFilter, setDomainFilter] = useState<string>('ALL');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');
  const [loading, setLoading] = useState<boolean>(false);
  const [evaluating, setEvaluating] = useState<boolean>(false);
  const [reviewingId, setReviewingId] = useState<string | null>(null);
  const [reviewerName, setReviewerName] = useState<string>('Municipal Traffic Cell Officer');
  const [newStatus, setNewStatus] = useState<RecommendationStatus>('UNDER_REVIEW');
  const [reviewNotes, setReviewNotes] = useState<string>('');
  const [submittingReview, setSubmittingReview] = useState<boolean>(false);
  const [expandedAuditId, setExpandedAuditId] = useState<string | null>(null);

  const loadData = async () => {
    try {
      setLoading(true);
      const [recs, sum] = await Promise.all([
        fetchRecommendations(
          domainFilter === 'ALL' ? undefined : domainFilter,
          statusFilter === 'ALL' ? undefined : statusFilter
        ),
        fetchAdvisorySummary()
      ]);
      setRecommendations(recs);
      setSummary(sum);
    } catch (err) {
      console.error('Failed to load advisory recommendations', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      loadData();
    }
  }, [isOpen, domainFilter, statusFilter]);

  if (!isOpen) return null;

  const handleTriggerEvaluate = async () => {
    try {
      setEvaluating(true);
      await triggerRuleEvaluation();
      await loadData();
    } catch (err) {
      console.error('Failed to evaluate rules', err);
    } finally {
      setEvaluating(false);
    }
  };

  const handleExecuteReview = async (recId: string) => {
    try {
      setSubmittingReview(true);
      await reviewRecommendation(recId, newStatus, reviewerName, reviewNotes);
      setReviewingId(null);
      setReviewNotes('');
      await loadData();
    } catch (err) {
      console.error('Failed to execute advisory review', err);
    } finally {
      setSubmittingReview(false);
    }
  };

  const getSeverityBadgeClass = (severity: RecommendationSeverity) => {
    switch (severity) {
      case 'CRITICAL':
        return 'badge-critical';
      case 'WARNING':
        return 'badge-warning';
      case 'INFO':
      default:
        return 'badge-info';
    }
  };

  const getStatusBadgeClass = (status: RecommendationStatus) => {
    switch (status) {
      case 'ACTIVE':
        return 'status-active';
      case 'UNDER_REVIEW':
        return 'status-review';
      case 'ACKNOWLEDGED':
        return 'status-acknowledged';
      case 'DISMISSED':
        return 'status-dismissed';
      default:
        return '';
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="advisory-modal-content"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-labelledby="advisory-title"
      >
        {/* Modal Header */}
        <div className="modal-header">
          <div className="modal-header-left">
            <h2 id="advisory-title" className="modal-title">
              Advisory Decision Support Center
            </h2>
            <span className="provenance-tag prov-predicted">EVIDENCE-BACKED ADVISORIES</span>
          </div>
          <button className="btn-close" onClick={onClose} aria-label="Close Advisory Center">
            &times;
          </button>
        </div>

        {/* Governance Mandate Banner */}
        <div className="governance-alert-banner">
          <div className="governance-icon">⚖️</div>
          <div className="governance-text">
            <strong>Mandatory Governance Policy:</strong> All recommendations generated by the twin rule engine
            are strictly advisory decision support. No automated actuation is permitted. Every operational action
            requires verified human authorization by municipal officials or facility managers.
          </div>
        </div>

        {/* Metrics Summary Strip */}
        {summary && (
          <div className="advisory-metrics-strip">
            <div className="advisory-metric-card">
              <span className="metric-label">Active Advisories</span>
              <span className="metric-val">{summary.totalActive}</span>
            </div>
            <div className="advisory-metric-card">
              <span className="metric-label">Critical Priority</span>
              <span className="metric-val text-critical">{summary.criticalCount}</span>
            </div>
            <div className="advisory-metric-card">
              <span className="metric-label">Warning Priority</span>
              <span className="metric-val text-warning">{summary.warningCount}</span>
            </div>
            <div className="advisory-metric-card">
              <span className="metric-label">Traffic Domain</span>
              <span className="metric-val">{summary.byDomain['TRAFFIC'] || 0}</span>
            </div>
            <div className="advisory-metric-card">
              <span className="metric-label">Energy Domain</span>
              <span className="metric-val">{summary.byDomain['ENERGY'] || 0}</span>
            </div>
            <button
              className="btn btn-secondary btn-evaluate"
              onClick={handleTriggerEvaluate}
              disabled={evaluating}
              title="Evaluate active twin state and forecasts against deterministic rules"
            >
              {evaluating ? 'Evaluating...' : '↻ Refresh Rules'}
            </button>
          </div>
        )}

        {/* Filter Controls */}
        <div className="advisory-filters-row">
          <div className="filter-group">
            <label className="filter-label">Domain:</label>
            <div className="filter-chips">
              {['ALL', 'TRAFFIC', 'ENERGY', 'ENVIRONMENT'].map((dom) => (
                <button
                  key={dom}
                  className={`chip-btn ${domainFilter === dom ? 'active' : ''}`}
                  onClick={() => setDomainFilter(dom)}
                >
                  {dom}
                </button>
              ))}
            </div>
          </div>

          <div className="filter-group">
            <label className="filter-label">Status:</label>
            <div className="filter-chips">
              {['ALL', 'ACTIVE', 'UNDER_REVIEW', 'ACKNOWLEDGED', 'DISMISSED'].map((st) => (
                <button
                  key={st}
                  className={`chip-btn ${statusFilter === st ? 'active' : ''}`}
                  onClick={() => setStatusFilter(st)}
                >
                  {st.replace('_', ' ')}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Recommendations List Body */}
        <div className="advisory-list-body">
          {loading ? (
            <div className="loading-state">Loading advisory records...</div>
          ) : recommendations.length === 0 ? (
            <div className="empty-state">
              <p>No recommendations match the selected filters.</p>
            </div>
          ) : (
            recommendations.map((rec) => (
              <div key={rec.recommendationId} className="advisory-card">
                <div className="advisory-card-header">
                  <div className="advisory-badges-left">
                    <span className="domain-pill">{rec.domain}</span>
                    <span className={`severity-pill ${getSeverityBadgeClass(rec.severity)}`}>
                      {rec.severity}
                    </span>
                    <span className={`status-pill ${getStatusBadgeClass(rec.status)}`}>
                      {rec.status.replace('_', ' ')}
                    </span>
                    <span className="rec-id-tag">{rec.recommendationId}</span>
                  </div>
                  <span className="rec-timestamp">
                    {new Date(rec.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>

                <h3 className="advisory-card-title">{rec.title}</h3>
                <p className="advisory-card-desc">{rec.description}</p>

                {/* Evidence Drill-Down Box */}
                <div className="advisory-evidence-box">
                  <div className="evidence-header">
                    <span className="evidence-title">Traceable Evidence</span>
                    <span className={`provenance-tag prov-${rec.evidence.sourceMode.toLowerCase()}`}>
                      {rec.evidence.sourceMode}
                    </span>
                  </div>
                  <div className="evidence-grid">
                    <div className="evidence-item">
                      <span className="ev-label">Target Entity:</span>
                      <span className="ev-val font-mono">{rec.targetEntityId.split(':').pop()}</span>
                    </div>
                    <div className="evidence-item">
                      <span className="ev-label">Trigger Rule:</span>
                      <span className="ev-val font-mono">{rec.triggerRule}</span>
                    </div>
                    <div className="evidence-item">
                      <span className="ev-label">Trigger Value:</span>
                      <span className="ev-val font-bold">
                        {rec.evidence.observedOrPredictedValue.toFixed(1)} {rec.evidence.unit} (Threshold: {rec.evidence.threshold.toFixed(1)} {rec.evidence.unit})
                      </span>
                    </div>
                    {rec.evidence.horizonMinutes && (
                      <div className="evidence-item">
                        <span className="ev-label">Forecast Horizon:</span>
                        <span className="ev-val">+{rec.evidence.horizonMinutes} minutes</span>
                      </div>
                    )}
                    {rec.evidence.modelVersion && (
                      <div className="evidence-item">
                        <span className="ev-label">Model Version:</span>
                        <span className="ev-val font-mono">{rec.evidence.modelVersion}</span>
                      </div>
                    )}
                    {rec.evidence.confidenceScore && (
                      <div className="evidence-item">
                        <span className="ev-label">Input Confidence:</span>
                        <span className="ev-val">{(rec.evidence.confidenceScore * 100).toFixed(0)}%</span>
                      </div>
                    )}
                  </div>
                </div>

                {/* Suggested Action Callout */}
                <div className="suggested-action-callout">
                  <div className="action-icon">💡</div>
                  <div className="action-content">
                    <span className="action-heading">Suggested Advisory Action:</span>
                    <p className="action-text">{rec.suggestedAction}</p>
                  </div>
                </div>

                {/* Interactive Action Buttons */}
                <div className="advisory-actions-bar">
                  <div className="action-btns-left">
                    {onSelectEntity && (
                      <button
                        className="btn btn-secondary btn-sm"
                        onClick={() => {
                          onSelectEntity(rec.targetEntityId);
                          onClose();
                        }}
                      >
                        Inspect on Map
                      </button>
                    )}
                    {rec.domain === 'TRAFFIC' && onOpenScenarioStudio && (
                      <button
                        className="btn btn-secondary btn-sm"
                        onClick={() => {
                          onOpenScenarioStudio();
                          onClose();
                        }}
                      >
                        Test in Scenario Studio
                      </button>
                    )}
                  </div>

                  <div className="action-btns-right">
                    <button
                      className="btn btn-secondary btn-sm"
                      onClick={() =>
                        setExpandedAuditId(expandedAuditId === rec.recommendationId ? null : rec.recommendationId)
                      }
                    >
                      Audit Trail ({rec.auditTrail.length})
                    </button>
                    <button
                      className="btn btn-primary btn-sm"
                      onClick={() => setReviewingId(reviewingId === rec.recommendationId ? null : rec.recommendationId)}
                    >
                      {reviewingId === rec.recommendationId ? 'Cancel Review' : 'Review / Update Status'}
                    </button>
                  </div>
                </div>

                {/* Inline Review Workflow Form */}
                {reviewingId === rec.recommendationId && (
                  <div className="review-workflow-panel">
                    <h4 className="review-title">Human Governance Review Form</h4>
                    <div className="review-inputs-grid">
                      <div className="form-group">
                        <label className="form-label">Reviewer Identity:</label>
                        <input
                          type="text"
                          className="form-input"
                          value={reviewerName}
                          onChange={(e) => setReviewerName(e.target.value)}
                          placeholder="e.g. Traffic Cell Officer"
                        />
                      </div>
                      <div className="form-group">
                        <label className="form-label">Target Review Status:</label>
                        <select
                          className="form-select"
                          value={newStatus}
                          onChange={(e) => setNewStatus(e.target.value as RecommendationStatus)}
                        >
                          <option value="UNDER_REVIEW">UNDER_REVIEW (Assessing field validity)</option>
                          <option value="ACKNOWLEDGED">ACKNOWLEDGED (Accepted / Action queued outside platform)</option>
                          <option value="DISMISSED">DISMISSED (Not applicable / False positive)</option>
                        </select>
                      </div>
                    </div>
                    <div className="form-group">
                      <label className="form-label">Review Justification / Decision Notes:</label>
                      <textarea
                        className="form-textarea"
                        rows={2}
                        value={reviewNotes}
                        onChange={(e) => setReviewNotes(e.target.value)}
                        placeholder="State operational reasoning, field verification observations, or dispatch notes..."
                      />
                    </div>
                    <div className="review-submit-row">
                      <button
                        className="btn btn-primary btn-sm"
                        disabled={submittingReview || !reviewerName.trim()}
                        onClick={() => handleExecuteReview(rec.recommendationId)}
                      >
                        {submittingReview ? 'Recording Audit...' : 'Submit Governance Decision'}
                      </button>
                    </div>
                  </div>
                )}

                {/* Chronological Audit Trail Drawer */}
                {expandedAuditId === rec.recommendationId && (
                  <div className="audit-trail-panel">
                    <h4 className="audit-title">Chronological Audit Log</h4>
                    <div className="audit-timeline">
                      {rec.auditTrail.map((entry, idx) => (
                        <div key={idx} className="audit-entry">
                          <div className="audit-meta">
                            <span className="audit-time">
                              {new Date(entry.timestamp).toLocaleString()}
                            </span>
                            <span className="audit-reviewer">Reviewed by: {entry.reviewer}</span>
                          </div>
                          <div className="audit-transition">
                            <span className="status-badge-sm">{entry.previousStatus}</span>
                            <span className="arrow">→</span>
                            <span className="status-badge-sm">{entry.newStatus}</span>
                          </div>
                          {entry.notes && <p className="audit-notes">"{entry.notes}"</p>}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
};
