import React from 'react';
import {
  Radio,
  RotateCcw,
  FlaskConical,
  TrendingUp,
  Clock,
  AlertOctagon
} from 'lucide-react';
import { SourceMode } from '../types/twin';

export type ProvenanceType = SourceMode | 'INVALID';

interface ProvenanceBadgeProps {
  mode: ProvenanceType | string;
  label?: string;
  subtitle?: string;
  tooltip?: string;
  className?: string;
  style?: React.CSSProperties;
}

export const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({
  mode,
  label,
  subtitle,
  tooltip,
  className = '',
  style
}) => {
  const normalizedMode = (mode || 'SIMULATION').toUpperCase() as ProvenanceType;

  const defaultTooltips: Record<string, string> = {
    LIVE: 'Live streaming telemetry from field sensors or calibrated mock feed',
    REPLAY: 'Historical recorded dataset replayed synchronously',
    SIMULATION: 'Synthetic microscopic simulation generated by Eclipse SUMO',
    PREDICTED: 'Near-term statistical forecast generated by XGBoost inference',
    STALE: 'Last known observation; no fresh updates received within threshold',
    INVALID: 'Record quarantined due to validation failure or schema anomaly'
  };

  const resolvedTooltip = tooltip || defaultTooltips[normalizedMode] || normalizedMode;

  const renderIcon = () => {
    switch (normalizedMode) {
      case 'LIVE':
        return <Radio size={12} aria-hidden="true" />;
      case 'REPLAY':
        return <RotateCcw size={12} aria-hidden="true" />;
      case 'SIMULATION':
        return <FlaskConical size={12} aria-hidden="true" />;
      case 'PREDICTED':
        return <TrendingUp size={12} aria-hidden="true" />;
      case 'STALE':
        return <Clock size={12} aria-hidden="true" />;
      case 'INVALID':
        return <AlertOctagon size={12} aria-hidden="true" />;
      default:
        return <FlaskConical size={12} aria-hidden="true" />;
    }
  };

  const badgeClass = `provenance-badge badge-${normalizedMode.toLowerCase()} ${className}`.trim();

  return (
    <span
      className={badgeClass}
      title={resolvedTooltip}
      role="status"
      aria-label={`Provenance: ${label || normalizedMode}${subtitle ? ` - ${subtitle}` : ''}`}
      style={style}
    >
      <span className="badge-icon">{renderIcon()}</span>
      <span className="badge-text">{label || normalizedMode}</span>
      {subtitle && (
        <>
          <span className="badge-separator" aria-hidden="true">·</span>
          <span className="badge-subtitle">{subtitle}</span>
        </>
      )}
    </span>
  );
};
