import React, { useState, useEffect } from 'react';
import {
  ShieldCheck,
  CheckCircle2,
  RotateCcw,
  Lightbulb
} from 'lucide-react';
import {
  AdvisoryRecommendation,
  AdvisorySummary,
  RecommendationStatus,
  RecommendationSeverity
} from '../../types/twin';
import {
  fetchRecommendations,
  fetchAdvisorySummary,
  reviewRecommendation,
  triggerRuleEvaluation
} from '../../services/api';

interface RecommendationsViewProps {
  onNavigateToEntity?: (entityId: string) => void;
  onNavigateToScenarios?: () => void;
  userRole?: string;
}

export const RecommendationsView: React.FC<RecommendationsViewProps> = ({
  onNavigateToEntity,
  onNavigateToScenarios,
  userRole
}) => {
  const [recommendations, setRecommendations] = useState<AdvisoryRecommendation[]>([]);
  const [summary, setSummary] = useState<AdvisorySummary | null>(null);
  const [domainFilter, setDomainFilter] = useState<string>('ALL');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');
  const [loading, setLoading] = useState<boolean>(true);
  const [evaluating, setEvaluating] = useState<boolean>(false);
  const [reviewingId, setReviewingId] = useState<string | null>(null);
  const [reviewerName, setReviewerName] = useState<string>(() => {
    return userRole || localStorage.getItem('municipal_role') || 'Municipal Analyst';
  });

  useEffect(() => {
    if (userRole) {
      setReviewerName(userRole);
    }
  }, [userRole]);

  const [newStatus, setNewStatus] = useState<RecommendationStatus>('UNDER_REVIEW');
  const [reviewNotes, setReviewNotes] = useState<string>('');
  const [submittingReview, setSubmittingReview] = useState<boolean>(false);
  const [expandedAuditId, setExpandedAuditId] = useState<string | null>(null);

  const loadData = async () => {
    try {
      setLoading(true);
      const [recs, sum] = await Promise.all([
        fetchRecommendations(
          domainFilter === 'ALL' ? undefined : domainFilter,
          statusFilter === 'ALL' ? undefined : statusFilter
        ),
        fetchAdvisorySummary()
      ]);
      setRecommendations(recs);
      setSummary(sum);
    } catch (err) {
      console.error('Failed to load advisory recommendations', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [domainFilter, statusFilter]);

  const handleTriggerEvaluate = async () => {
    try {
      setEvaluating(true);
      await triggerRuleEvaluation();
      await loadData();
    } catch (err) {
      console.error('Failed to evaluate rules', err);
    } finally {
      setEvaluating(false);
    }
  };

  const handleExecuteReview = async (recId: string) => {
    try {
      setSubmittingReview(true);
      await reviewRecommendation(recId, newStatus, reviewerName, reviewNotes);
      setReviewingId(null);
      setReviewNotes('');
      await loadData();
    } catch (err) {
      console.error('Failed to execute advisory review', err);
    } finally {
      setSubmittingReview(false);
    }
  };

  const getSeverityBadgeClass = (severity: RecommendationSeverity) => {
    switch (severity) {
      case 'CRITICAL':
        return 'badge-critical';
      case 'WARNING':
        return 'badge-warning';
      case 'INFO':
      default:
        return 'badge-info';
    }
  };

  const getStatusBadgeClass = (status: RecommendationStatus) => {
    switch (status) {
      case 'ACTIVE':
        return 'status-active';
      case 'UNDER_REVIEW':
        return 'status-review';
      case 'ACKNOWLEDGED':
        return 'status-acknowledged';
      case 'DISMISSED':
        return 'status-dismissed';
      default:
        return '';
    }
  };

  return (
    <div className="view-container recommendations-view">
      {/* View Header */}
      <div className="view-header">
        <div>
          <h1 className="view-title">Advisory Decision Support & Governance Center</h1>
          <p className="view-subtitle">
            Evidence-backed municipal advisory queue, human authorization audit log, and multi-domain operational recommendations.
          </p>
        </div>
        <div className="view-header-badges">
          <span className="provenance-badge badge-predicted">EVIDENCE-BACKED RULES</span>
          <span className="provenance-badge badge-live">HUMAN AUTHORIZATION REQUIRED</span>
        </div>
      </div>

      {/* Mandatory Governance Alert Banner per UI_UX_SPEC §13 */}
      <div className="integrity-caveat-banner">
        <ShieldCheck size={20} color="#0F4C5C" style={{ flexShrink: 0 }} />
        <div>
          <strong>Mandatory Governance Policy (UI_UX_SPEC §13.2):</strong> All recommendations generated by the twin rule engine are strictly advisory decision support. Automated actuation is strictly prohibited. Every operational intervention requires verified human authorization by municipal traffic police or facility engineering personnel.
        </div>
      </div>

      {/* High-Level Metrics Strip */}
      {summary && (
        <div className="quick-metrics-row-four" style={{ marginBottom: '16px' }}>
          <div className="metric-box">
            <span className="metric-box-label">Active Advisories</span>
            <span className="metric-box-val" style={{ color: summary.totalActive > 0 ? '#0F4C5C' : '#10B981' }}>
              {summary.totalActive}
            </span>
            <span className="metric-box-sub">Requiring operator review</span>
          </div>

          <div className="metric-box">
            <span className="metric-box-label">High Attention / Critical</span>
            <span className="metric-box-val" style={{ color: summary.criticalCount > 0 ? '#EF4444' : '#10B981' }}>
              {summary.criticalCount}
            </span>
            <span className="metric-box-sub">Thresholds exceeded</span>
          </div>

          <div className="metric-box">
            <span className="metric-box-label">Traffic Domain Advisories</span>
            <span className="metric-box-val" style={{ color: '#0F4C5C' }}>
              {summary.byDomain['TRAFFIC'] || 0}
            </span>
            <span className="metric-box-sub">Nagar Road corridor</span>
          </div>

          <div className="metric-box">
            <span className="metric-box-label">Energy Domain Advisories</span>
            <span className="metric-box-val" style={{ color: '#0F4C5C' }}>
              {summary.byDomain['ENERGY'] || 0}
            </span>
            <span className="metric-box-sub">Phoenix Marketcity zone</span>
          </div>
        </div>
      )}

      {/* Filter Chips Bar */}
      <div className="analytics-filter-bar">
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px', flexWrap: 'wrap' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <span style={{ fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--color-text-secondary)' }}>
              Domain:
            </span>
            <div className="filter-chips">
              {['ALL', 'TRAFFIC', 'ENERGY', 'ENVIRONMENT'].map((dom) => (
                <button
                  key={dom}
                  className={`chip-btn ${domainFilter === dom ? 'active' : ''}`}
                  onClick={() => setDomainFilter(dom)}
                >
                  {dom}
                </button>
              ))}
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <span style={{ fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--color-text-secondary)' }}>
              Status:
            </span>
            <div className="filter-chips">
              {['ALL', 'ACTIVE', 'UNDER_REVIEW', 'ACKNOWLEDGED', 'DISMISSED'].map((st) => (
                <button
                  key={st}
                  className={`chip-btn ${statusFilter === st ? 'active' : ''}`}
                  onClick={() => setStatusFilter(st)}
                >
                  {st.replace('_', ' ')}
                </button>
              ))}
            </div>
          </div>
        </div>

        <button
          className="btn-select-sm"
          onClick={handleTriggerEvaluate}
          disabled={evaluating}
          style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
        >
          <RotateCcw size={14} className={evaluating ? 'animate-spin' : ''} />
          <span>{evaluating ? 'Evaluating...' : 'Re-Evaluate Rules'}</span>
        </button>
      </div>

      {/* Recommendations Feed List */}
      <div className="advisory-full-list" style={{ marginTop: '16px' }}>
        {loading ? (
          <div className="empty-results-box" style={{ padding: '36px' }}>
            <span className="btn-spinner" />
            <span style={{ marginTop: '8px' }}>Loading advisory records...</span>
          </div>
        ) : recommendations.length === 0 ? (
          <div className="empty-results-box" style={{ padding: '36px' }}>
            <CheckCircle2 size={32} color="#10B981" />
            <p style={{ marginTop: '8px', fontWeight: 600 }}>All Clear — No Active Advisories</p>
            <p style={{ fontSize: '12px', color: 'var(--color-text-secondary)' }}>
              All telemetry metrics are currently operating within nominal baseline safety envelopes.
            </p>
          </div>
        ) : (
          recommendations.map((rec) => (
            <div key={rec.recommendationId} className="advisory-card" style={{ marginBottom: '16px' }}>
              <div className="advisory-card-header">
                <div className="advisory-badges-left">
                  <span className="domain-pill">{rec.domain}</span>
                  <span className={`severity-pill ${getSeverityBadgeClass(rec.severity)}`}>
                    {rec.severity}
                  </span>
                  <span className={`status-pill ${getStatusBadgeClass(rec.status)}`}>
                    {rec.status.replace('_', ' ')}
                  </span>
                  <span className="rec-id-tag font-mono">{rec.recommendationId}</span>
                </div>
                <span className="rec-timestamp">
                  Generated: {new Date(rec.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>

              <h3 className="advisory-card-title">{rec.title}</h3>
              <p className="advisory-card-desc">{rec.description}</p>

              {/* Evidence Drill-Down Box */}
              <div className="advisory-evidence-box">
                <div className="evidence-header">
                  <span className="evidence-title">Traceable Rule Evidence</span>
                  <span className={`provenance-tag prov-${rec.evidence.sourceMode.toLowerCase()}`}>
                    {rec.evidence.sourceMode}
                  </span>
                </div>
                <div className="evidence-grid">
                  <div className="evidence-item">
                    <span className="ev-label">Target Entity:</span>
                    <span className="ev-val font-mono">{rec.targetEntityId.split(':').pop()}</span>
                  </div>
                  <div className="evidence-item">
                    <span className="ev-label">Trigger Rule:</span>
                    <span className="ev-val font-mono">{rec.triggerRule}</span>
                  </div>
                  <div className="evidence-item">
                    <span className="ev-label">Trigger Value:</span>
                    <span className="ev-val font-bold">
                      {rec.evidence.observedOrPredictedValue.toFixed(1)} {rec.evidence.unit} (Threshold: {rec.evidence.threshold.toFixed(1)} {rec.evidence.unit})
                    </span>
                  </div>
                  {rec.evidence.horizonMinutes && (
                    <div className="evidence-item">
                      <span className="ev-label">Forecast Horizon:</span>
                      <span className="ev-val">+{rec.evidence.horizonMinutes} minutes</span>
                    </div>
                  )}
                  {rec.evidence.modelVersion && (
                    <div className="evidence-item">
                      <span className="ev-label">Model Version:</span>
                      <span className="ev-val font-mono">{rec.evidence.modelVersion}</span>
                    </div>
                  )}
                  {rec.evidence.confidenceScore && (
                    <div className="evidence-item">
                      <span className="ev-label">Input Confidence:</span>
                      <span className="ev-val">{(rec.evidence.confidenceScore * 100).toFixed(0)}%</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Suggested Action Callout */}
              <div className="suggested-action-callout">
                <div className="action-icon"><Lightbulb size={16} color="var(--color-primary)" /></div>
                <div className="action-content">
                  <span className="action-heading">Suggested Advisory Intervention:</span>
                  <p className="action-text">{rec.suggestedAction}</p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="advisory-actions-bar">
                <div className="action-btns-left">
                  {onNavigateToEntity && (
                    <button
                      className="btn btn-secondary btn-sm"
                      onClick={() => onNavigateToEntity(rec.targetEntityId)}
                    >
                      Inspect on Map
                    </button>
                  )}
                  {rec.domain === 'TRAFFIC' && onNavigateToScenarios && (
                    <button
                      className="btn btn-secondary btn-sm"
                      onClick={onNavigateToScenarios}
                    >
                      Test in Scenario Studio
                    </button>
                  )}
                </div>

                <div className="action-btns-right">
                  <button
                    className="btn btn-secondary btn-sm"
                    onClick={() =>
                      setExpandedAuditId(expandedAuditId === rec.recommendationId ? null : rec.recommendationId)
                    }
                  >
                    Audit Log ({rec.auditTrail.length})
                  </button>
                  <button
                    className="btn btn-primary btn-sm"
                    onClick={() => setReviewingId(reviewingId === rec.recommendationId ? null : rec.recommendationId)}
                  >
                    {reviewingId === rec.recommendationId ? 'Cancel Review' : 'Authorize / Update Status'}
                  </button>
                </div>
              </div>

              {/* Inline Human Review Form */}
              {reviewingId === rec.recommendationId && (
                <div className="review-workflow-panel">
                  <h4 className="review-title">Human Governance Authorization Form</h4>
                  <div className="review-inputs-grid">
                    <div className="form-group">
                      <label className="form-label">Reviewer Role & Designation:</label>
                      <input
                        type="text"
                        className="form-input"
                        value={reviewerName}
                        onChange={(e) => setReviewerName(e.target.value)}
                        placeholder="e.g. Traffic Cell Officer"
                      />
                    </div>
                    <div className="form-group">
                      <label className="form-label">Authorization Decision:</label>
                      <select
                        className="form-select"
                        value={newStatus}
                        onChange={(e) => setNewStatus(e.target.value as RecommendationStatus)}
                      >
                        <option value="UNDER_REVIEW">UNDER_REVIEW (Assessing field validity)</option>
                        <option value="ACKNOWLEDGED">ACKNOWLEDGED (Accepted / Action queued outside platform)</option>
                        <option value="DISMISSED">DISMISSED (Not applicable / False positive)</option>
                      </select>
                    </div>
                  </div>
                  <div className="form-group">
                    <label className="form-label">Operational Notes & Justification:</label>
                    <textarea
                      className="form-textarea"
                      rows={2}
                      value={reviewNotes}
                      onChange={(e) => setReviewNotes(e.target.value)}
                      placeholder="State operational reasoning, field verification observations, or dispatch notes..."
                    />
                  </div>
                  <div className="review-submit-row">
                    <button
                      className="btn btn-primary btn-sm"
                      disabled={submittingReview || !reviewerName.trim()}
                      onClick={() => handleExecuteReview(rec.recommendationId)}
                    >
                      {submittingReview ? 'Recording Audit...' : 'Submit Human Authorization'}
                    </button>
                  </div>
                </div>
              )}

              {/* Audit Trail Drawer */}
              {expandedAuditId === rec.recommendationId && (
                <div className="audit-trail-panel">
                  <h4 className="audit-title">Chronological Audit Log</h4>
                  <div className="audit-timeline">
                    {rec.auditTrail.map((entry, idx) => (
                      <div key={idx} className="audit-entry">
                        <div className="audit-meta">
                          <span className="audit-time font-mono">
                            {new Date(entry.timestamp).toLocaleString()}
                          </span>
                          <span className="audit-reviewer">Authorized by: {entry.reviewer}</span>
                        </div>
                        <div className="audit-transition">
                          <span className="status-badge-sm">{entry.previousStatus}</span>
                          <span className="arrow">→</span>
                          <span className="status-badge-sm">{entry.newStatus}</span>
                        </div>
                        {entry.notes && <p className="audit-notes">"{entry.notes}"</p>}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
};
